#!/usr/bin/env python3
"""Mutation kill check: prove the Direct Mode suite pins each load-bearing
guard, not merely that the code passes today.

For each mutation the repository is copied to a scratch directory with ONE
guard in the contract mechanically broken, and the whole Direct Mode suite
runs against the copy. A mutation is KILLED when the suite fails and SURVIVED
when it passes (an unpinned guard). The run starts with an accept-control:
the unmodified copy must pass, or every kill would be vacuous.

Anchors are code TEXT, never line numbers. An anchor that is not found
exactly once is reported as ANCHOR MISSING - the guard moved or was deleted,
which is its own finding.

Run:  python scripts/mutation_check.py              (full sweep)
      python scripts/mutation_check.py --anchors    (anchor check only)
      python scripts/mutation_check.py --only gate  (names containing "gate";
                                                     separate several with |)
      python scripts/mutation_check.py --jobs 3     (three scratch copies)
"""

from __future__ import annotations

import pathlib
import shutil
import subprocess
import sys
import tempfile
import threading

ROOT = pathlib.Path(__file__).resolve().parents[1]
CONTRACT = "contracts/bounty_acceptance.py"


def off(condition: str) -> tuple:
    """(anchor, replacement) turning one `if` line into `if False:`."""
    head = condition[:len(condition) - len(condition.lstrip())]
    keyword = condition.lstrip().split(" ", 1)[0]
    return (condition + "\n", head + keyword + " False:\n")


def m(name: str, anchor: str, replacement: str = None) -> tuple:
    if replacement is None:
        anchor, replacement = off(anchor)
    return (name, anchor, replacement)


def off2(first: str, second: str) -> tuple:
    """(anchor, replacement) for an `if` line that occurs more than once: the
    line after it makes the anchor unique."""
    head = first[:len(first) - len(first.lstrip())]
    keyword = first.lstrip().split(" ", 1)[0]
    return (first + "\n" + second, head + keyword + " False:\n" + second)


def m2(name: str, first: str, second: str) -> tuple:
    anchor, replacement = off2(first, second)
    return (name, anchor, replacement)


MUTATIONS = [
    ('bounty: the shortest window is one a party can act in',
     'MIN_WINDOW = 900 ',
     'MIN_WINDOW = 60 '),
    ('bounty: contradictory checks are refused',
     '    return _checks_conflict(checks)',
     '    return ""'),
    ('bounty: a required passage that contains a forbidden one',
     '                    and _passage_in(a["value"], b["value"]):',
     '                    and False:'),
    ('check: a pair read by its small letter has its reading',
     '    for how in READINGS:\n        if _find_run',
     '    for how in (READ_BY_CAPITAL, READ_AS_SHOWN):\n        if _find_run'),
    ('check: a word spelled with both letters of a pair has its reading',
     '    for how in READINGS:\n        if _find_run',
     '    for how in (READ_BY_CAPITAL, READ_BY_SMALL):\n        if _find_run'),
    ('check: a pair read by its capital has its reading',
     '    for how in READINGS:\n        if _find_run',
     '    for how in (READ_BY_SMALL, READ_AS_SHOWN):\n        if _find_run'),
    ('check: letterlike symbols are read as their letters',
     '                  + [(chr(code), LETTERLIKE[code]) for code in LETTERLIKE])',
     '                  )'),
    ('check: a letter and its other case are one letter',
     '            if len(other) == 1 and other != letter:\n                union(letter, other)',
     '            if False:\n                union(letter, other)'),
    ('check: a class holds one Latin letter',
     '        if a == b or (latin[a] != "" and latin[b] != "" and latin[a] != latin[b]):',
     '        if a == b:'),
    ('check: fullwidth letters do not hide a word',
     '    if 0xFF01 <= code <= 0xFF5E:',
     '    if False:'),
    ('check: circled letters do not hide a word',
     '    if 0x24D0 <= code <= 0x24E9:',
     '    if False:'),
    ("check: a document's words are taken once",
     '    if "readings" not in doc:',
     '    if True:'),
    ('text: a control character is nothing',
     '            out.append(" " if ch.isspace() else "")       # a control character is nothing',
     '            out.append(ch)'),
    ('text: a dropped box leaves a gap',
     'out.append("" if raw in SILENT_TAGS else joiner)',
     'out.append("")'),
    ('text: a dropped script leaves nothing',
     'out.append("" if raw in SILENT_TAGS else joiner)',
     'out.append(joiner)'),
    ('count: a comma or letter leads into no thousands number',
     '    if start > 0 and text[start - 1].isalpha():\n        return False',
     '    if False:\n        return False'),
    ('text: control and line-separator characters',
     '        if code < 32 or 127 <= code <= 159 or code in (0x2028, 0x2029):\n            return label',
     '        if code < 32 or code == 127:\n            return label'),
    ('text: no party text addresses the evaluator',
     '    if _evaluator_hits(value) or _hidden_hits(value):\n',
     '    if False:\n'),
    ('text: the published markers are matched',
     '    return len(_marker_hits_in(_scan_form(text))) > 0',
     '    return False'),
    ('text: JSON escapes only in a document that is JSON',
     '    elif _is_json(text.lstrip(chr(0xFEFF))):',
     '    elif text.lstrip()[:1] in ("{", "["):'),
    ('mirror: not a URL twice',
     '            if canonical_url in item["urls"]:\n',
     '            if False:\n'),
    ('read: only the pinned bytes are the evidence',
     '        if body is not None and hashlib.sha256(body).hexdigest() != item["sha256"]:\n',
     '        if False:\n'),
    ('read: every address is tried',
     '    for via, url in enumerate(item["urls"]):',
     '    for via, url in enumerate(item["urls"][:1]):'),
    ('read: one unfetched document makes the round unreadable',
     '    if any(s["status"] not in READABLE for s in sources):\n',
     '    if False:\n'),
    ('read: the panel reads its share and no more',
     'docs[evidence_id]["text"][:share]',
     'docs[evidence_id]["text"]'),
    ('read: the panel is told when it sees a part',
     '                      and len(shown) == len(docs[evidence_id]["text"])})',
     '                      })'),
    ('panel: a state nobody defined is no answer',
     '    if state not in STATES:\n        return None',
     '    if state not in STATES:\n        return finding'),
    ('panel: a skipped requirement is no answer',
     '    if not isinstance(entry, dict):\n        return None',
     '    if not isinstance(entry, dict):\n        return finding'),
    ('check: at least that many words',
     '        return MET if _count_words(doc["text"]) >= value else NOT_MET',
     '        return MET if _count_words(doc["text"]) > value else NOT_MET'),
    ('check: a JSON object is an object',
     '            return MET if isinstance(parsed, dict) else NOT_MET',
     '            return MET'),
    ('check: a JSON array is an array',
     '            return MET if isinstance(parsed, list) else NOT_MET',
     '            return MET'),
    ('check: a file that does not parse is not JSON',
     '        except Exception:\n            return NOT_MET\n        if value == "object":',
     '        except Exception:\n            return MET\n        if value == "object":'),
    ('check: a passage is found by its words',
     '    return MET if found == (kind == CHECK_CONTAINS) else NOT_MET',
     '    return MET if found != (kind == CHECK_CONTAINS) else NOT_MET'),
    ('count: a Han or kana character is a word',
     '        if _is_ideograph(ord(ch)):\n            count = count + 1',
     '        if False:\n            count = count + 1'),
    ('count: an apostrophe stays inside a word',
     '        if inside and not joined and ch in "\'" + chr(0x2019) and prev.isalpha() \\\n                and nxt.isalpha():',
     '        if False:'),
    ('count: a point stays inside a number',
     '        if inside and ch == "." and prev.isdigit() and nxt.isdigit():\n',
     '        if False:\n'),
    ('count: a thousands comma stays inside a number',
     '        if inside and ch == "," and prev.isdigit() and _groups_thousands(text, i):\n',
     '        if False:\n'),
    ('count: any other comma separates two values',
     '    return re.fullmatch("[0-9]{1,3}(,[0-9]{3})+", run) is not None \\\n        and at - start < len(run)',
     '    return True'),
    ('count: a sign written on a letter stays in its word',
     '        if inside and _joins_word(ord(ch)):\n',
     '        if False:\n'),
    ('text: characters that take no space are removed',
     '    text = _visible(_normalize(raw, html))',
     '    text = _normalize(raw, html)'),
    ('text: a letter that renders as a gap is the gap',
     '        elif code in BLANK_LETTERS or code == 0x3000:',
     '        elif False:'),
    ('text: an inline tag does not split a word',
     'out.append(joiner if _block_tag(lower, j) else "")',
     'out.append(joiner)'),
    ('text: a block tag separates',
     'out.append(joiner if _block_tag(lower, j) else "")',
     'out.append("")'),
    ('text: a custom element is not a block',
     '        return False                      # a custom element',
     '        return True                       # a custom element'),
    ('text: a Han or kana character is a word of a passage',
     '        if _is_ideograph(ord(ch)):\n            if current:',
     '        if False:\n            if current:'),
    ('text: an escaped backslash begins no escape',
     '        if body in "/" + chr(34) + chr(92):',
     '        if False:'),
    ('text: more characters that take no space',
     ' or 0x2065 <= code <= 0x206F \\\n',
     ' \\\n'),
    ('check: mathematical letters do not hide a word',
     '    if 0x1D400 <= code <= 0x1D6A3:',
     '    if False:'),
    ('check: a byte-order mark is not part of a JSON document',
     'json.loads(doc["raw"].lstrip(chr(0xFEFF)), parse_constant=_not_json)',
     'json.loads(doc["raw"], parse_constant=_not_json)'),
    ('check: NaN is not JSON',
     'json.loads(doc["raw"].lstrip(chr(0xFEFF)), parse_constant=_not_json)',
     'json.loads(doc["raw"].lstrip(chr(0xFEFF)))'),
    ('count: one apostrophe to a word',
     '            joined = True          # one to a word: a chain of them joins nothing',
     '            pass'),
    ('count: Tibetan punctuation separates',
     '        return 0x0F71 <= code <= 0x0F84 or 0x0F86 <= code <= 0x0FBC',
     '        return True'),
    ('read: the budget not needed by a short file goes to a long one',
     '        share = min(length, left // (len(lengths) - index))',
     '        share = min(length, PANEL_BUDGET // len(lengths))'),
    ('panel: only so many quotes are tried',
     '    for rq in raw_quotes[:MAX_QUOTES * 2]:',
     '    for rq in raw_quotes:'),
    ('panel: only so many cuts are tried',
     '    cuts = _cuts(text)[:MAX_CUTS] if',
     '    cuts = _cuts(text) if'),
    ('panel: a quote is clean before it is kept',
     '        if not _quote_clean(cut):\n            continue',
     '        if False:\n            continue'),
    ('gate: a stored quote is clean',
     ' or not _quote_clean(q["text"]):',
     ' or False:'),
    ('gate: markers are strings before they are sorted',
     '            or not all(isinstance(entry, str) for entry in p["markers"]):',
     '            or False:'),
    ("gate: the leader's payload is parsed",
     '        if parsed is None:\n',
     '        if False:\n'),
    ('gate: a quote is one grounded passage',
     '        if q in seen or _spliced(q["text"]) or not _quote_grounded(q, eligible, tokens):\n',
     '        if False:\n'),
    ('gate: only MET carries quotes',
     '    return f["quotes"] == []',
     '    return True'),
    ("gate: the address that answered is one of the document's",
     '            or not (0 <= s["via"] < len(item["urls"])):',
     '            or False:'),
    ('gate: an unfetched source carries nothing',
     '        return s["raw_sha256"] == "" and s["content_digest"] == "" and s["title"] == "" \\\n            and s["truncated"] is False and s["via"] == -1',
     '        return True'),
    ('compare: what was read',
     '            print("[DISAGREE] evidence: " + difference)\n            return False',
     '            print("[DISAGREE] evidence: " + difference)\n            return True'),
    ('compare: what it leads to',
     '            print("[DISAGREE] consequence: " + difference)\n            return False',
     '            print("[DISAGREE] consequence: " + difference)\n            return True'),
    ('derive: an unusable answer decides nothing (inherited)',
     '    elif payload["panel_state"] == PANEL_INVALID:\n',
     '    elif False:\n'),
    ('bounty: a field type from the list',
     '        if not isinstance(entry["type"], str) or entry["type"] not in FIELD_TYPES:\n',
     '        if False:\n'),
    ('bounty: required is a boolean',
     '        if not isinstance(entry["required"], bool):\n',
     '        if False:\n'),
    ('bounty: a check names a listed field (inherited)',
     '    if not isinstance(check["field"], str) or check["field"] not in fields:\n',
     '    if False:\n'),
    ('bounty: an endpoint carries no query string',
     '        if "?" in canonical_url:\n',
     '        if False:\n'),
    ('bounty: the contest window is bounded',
     'MIN_WINDOW = 900 ',
     'MIN_WINDOW = 60 '),
    ('bounty: nothing a reader cannot see',
     '        if _visible(line) != " ".join(line.split()) or chr(0xAD) in line:\n',
     '        if False:\n'),
    ('submission: every required field is there',
     '            if field["required"]:\n',
     '            if False:\n'),
    ('evaluate: a round that decides nothing is on the record',
     '            submission.open_round = derived["reason_code"]',
     '            pass'),
    ('evaluate: a reading clears the open round',
     '            submission.open_round = ""',
     '            pass'),
    ('round: a reading has its time',
     '            submission.read_at = now',
     '            pass'),
    ('end: a verdict that rests on no reading has no reading time',
     '            submission.read_at = ""',
     '            pass'),
    ('check: lookalike letters do not hide a word',
     '    return _word_tokens(_fold_lookalikes(text, how))',
     '    return _word_tokens(text)'),
    ('compare: a round that decides nothing is agreed by its reason',
     '    if own["panel_reason"] in UNAVAILABLE_REASONS:\n',
     '    if False:\n'),
    ('bounty: exactly its keys',
     '    if tuple(sorted(bounty.keys())) != BOUNTY_KEYS:\n',
     '    if False:\n'),
    ('bounty: the reward is bounded',
     '    if not _int_in(bounty["reward"], MIN_REWARD, MAX_REWARD):\n',
     '    if False:\n'),
    ('bounty: a bond is at most the reward',
     '    if not _int_in(bounty["bond"], 0, bounty["reward"]):\n',
     '    if not _int_in(bounty["bond"], 0, MAX_REWARD):\n'),
    ('bounty: a bond is not negative',
     '    if not _int_in(bounty["bond"], 0, bounty["reward"]):\n',
     '    if not _int_in(bounty["bond"], -1, bounty["reward"]):\n'),
    ('bounty: documents are hosted somewhere named',
     '            ("document_hosts", 1, MAX_HOSTS, "where a document may be hosted"),',
     '            ("document_hosts", 0, MAX_HOSTS, "where a document may be hosted"),'),
    ('bounty: host lists are bounded and well formed',
     '        if not isinstance(hosts, list) or len(hosts) < least or len(hosts) > most \\\n                or len(set(str(h) for h in hosts)) != len(hosts) \\\n                or not all(_valid_domain(h) for h in hosts):\n',
     '        if not isinstance(hosts, list):\n'),
    ('bounty: submit_by is a time',
     '    if _iso_epoch(bounty["submit_by"]) is None:\n',
     '    if False:\n'),
    ('bounty: windows are bounded',
     '        if not _int_in(bounty[field], least, MAX_WINDOW):\n',
     '        if False:\n'),
    ('bounty: a title carries nothing unseen',
     '    if chr(0xFEFF) in value:\n',
     '    if False:\n'),
    ('bounty: fields are counted by type',
     '    if counts[FIELD_DOCUMENT] > MAX_DOCUMENTS:\n',
     '    if False:\n'),
    ('bounty: endpoints are bounded',
     '    if counts[FIELD_ENDPOINT] > MAX_ENDPOINTS:\n',
     '    if False:\n'),
    ('bounty: a field id is distinct and not reserved',
     '        if not _valid_ident(entry["id"]) or entry["id"] in seen \\\n                or entry["id"] in RESERVED_IDS:\n            return where + " id must be a distinct lowercase identifier, and not one of: " \\\n                + ", ".join(RESERVED_IDS)\n        seen.append(entry["id"])\n        err = _plain_error(entry["label"]',
     '        seen.append(entry["id"])\n        err = _plain_error(entry["label"]'),
    ('bounty: a field has a type',
     '        if not isinstance(entry["type"], str) or entry["type"] not in FIELD_TYPES:\n            return where + " type must be one of: " + ", ".join(FIELD_TYPES)\n',
     ''),
    ('bounty: requirements are bounded',
     '    if not isinstance(values, list) or len(values) < 1 or len(values) > MAX_REQUIREMENTS:\n',
     '    if not isinstance(values, list) or len(values) < 1:\n'),
    ('bounty: a requirement has exactly its keys',
     '        if tuple(sorted(entry.keys())) != keys:\n            return where + " needs exactly the keys: " + ", ".join(keys)\n        if not _valid_ident(entry["id"]) or entry["id"] in seen \\\n                or entry["id"] in RESERVED_IDS:\n            return where + " id must be a distinct lowercase identifier, and not one of: " \\\n                + ", ".join(RESERVED_IDS)\n        seen.append(entry["id"])\n        err = _plain_error(entry["text"]',
     '        seen.append(entry["id"])\n        err = _plain_error(entry["text"]'),
    ('bounty: a check reads a field every deliverable has',
     '            if not required[entry["check"]["field"]]:\n',
     '            if False:\n'),
    ('bounty: a judged requirement needs a required document',
     '        elif not any(fields[f] == FIELD_DOCUMENT and required[f] for f in fields):\n',
     '        elif False:\n'),
    ('bounty: an optional document does not carry a judged requirement',
     '        elif not any(fields[f] == FIELD_DOCUMENT and required[f] for f in fields):\n',
     '        elif not any(fields[f] == FIELD_DOCUMENT for f in fields):\n'),
    ('bounty: a check names a listed field',
     '    if not isinstance(check["field"], str) or check["field"] not in fields:\n',
     '    if not isinstance(check["field"], str):\n'),
    ('bounty: an endpoint check calls an endpoint',
     '        if fields[check["field"]] != FIELD_ENDPOINT:\n',
     '        if False:\n'),
    ('bounty: a document check reads a document',
     '    if fields[check["field"]] != FIELD_DOCUMENT:\n',
     '    if False:\n'),
    ('bounty: a check has exactly its keys',
     '    if tuple(sorted(check.keys())) != keys:\n',
     '    if False:\n'),
    ('bounty: a status a check names is one a service can be asked for',
     '            if not _status_allowed(value):\n',
     '            if not _is_int(value):\n'),
    ('bounty: a redirect is not named',
     '    return any(low <= value <= high for low, high in STATUS_RANGES)',
     '    return 200 <= value <= 499'),
    ('bounty: a momentary status is not named',
     '    if not _is_int(value) or value in MOMENTARY_STATUSES:\n',
     '    if not _is_int(value):\n'),
    ('bounty: an exact value is printable ASCII',
     '        if ord(ch) < 32 or ord(ch) > 126:\n',
     '        if False:\n'),
    ('bounty: an exact value has no space at its ends',
     '    if value != value.strip():\n        return where + " check value must not begin or end with a space"\n    if _evaluator_hits(value):',
     '    if _evaluator_hits(value):'),
    ('bounty: an exact value does not address the evaluator',
     '    if _evaluator_hits(value):\n',
     '    if False:\n'),
    ('bounty: an exact value is bounded',
     '    if not isinstance(value, str) or len(value) < 1 or len(value) > VALUE_CAP:\n',
     '    if not isinstance(value, str):\n'),
    ('bounty: a JSON shape is one of three',
     '        if kind == CHECK_RESPONSE_JSON:\n            if not isinstance(value, str) or value not in JSON_SHAPES:\n',
     '        if kind == CHECK_RESPONSE_JSON:\n            if False:\n'),
    ('bounty: a word count is bounded',
     '        if not _int_in(value, 1, BODY_BYTES_CAP // 2 - 1):\n',
     '        if False:\n'),
    ('bounty: a passage has a word',
     '    if not _has_a_word(value):\n',
     '    if False:\n'),
    ('bounty: a path begins with a slash and is bounded',
     '    if not isinstance(path, str) or len(path) < 1 or len(path) > PATH_CAP \\\n            or not path.startswith("/"):\n',
     '    if not isinstance(path, str):\n'),
    ('bounty: a path is plain',
     '        if ch not in PATH_CHARS:\n',
     '        if False:\n'),
    ('bounty: a path has no dot-segments',
     '    err, _canonical_url = _url_parts("https://host.example" + path)\n    if err != "":\n',
     '    err = ""\n    if err != "":\n'),
    ('conflict: the same check twice',
     '            if i < j and a == b:\n',
     '            if False:\n'),
    ('conflict: a required passage that holds a forbidden one',
     '            if a["type"] == CHECK_CONTAINS and b["type"] == CHECK_NOT_CONTAINS \\\n                    and _passage_in(a["value"], b["value"]):\n',
     '            if False:\n'),
    ('conflict: one path one status',
     '                if a["type"] == b["type"] == CHECK_RESPONDS and a["value"] != b["value"]:\n',
     '                if False:\n'),
    ('conflict: a body check needs a 200',
     '                if a["type"] == CHECK_RESPONDS and a["value"] != 200 \\\n                        and b["type"] != CHECK_RESPONDS:\n',
     '                if False:\n'),
    ('conflict: an answer is one shape',
     '                if a["type"] == b["type"] == CHECK_RESPONSE_JSON \\\n                        and (a["value"], b["value"]) == ("array", "object"):\n',
     '                if False:\n'),
    ('conflict: an array has no keys',
     '                if a["type"] == CHECK_RESPONSE_JSON and a["value"] == "array" \\\n                        and b["type"] == CHECK_RESPONSE_JSON_KEY:\n',
     '                if False:\n'),
    ('conflict: only on one path',
     '                    and a["path"] == b["path"]:\n',
     '                    and True:\n'),
    ('conflict: only on one field',
     '            if a["field"] != b["field"]:\n                continue\n            pair',
     '            pair'),
    ('submission: exactly its keys',
     '    if tuple(sorted(raw.keys())) != SUBMISSION_KEYS:\n',
     '    if False:\n'),
    ('submission: only listed fields',
     '        if key not in listed:\n',
     '        if False:\n'),
    ('submission: every required field',
     '            if field["required"]:\n                return (where + " is required by the bounty", None, None)\n',
     ''),
    ('submission: an endpoint runs where the bounty allows',
     '            err, canonical_url = _admitted_url(value, bounty, True)\n',
     '            err, canonical_url = _url_parts(value)\n'),
    ('submission: an endpoint has its own hosts',
     '    allowed = bounty["endpoint_hosts"] if endpoint else bounty["document_hosts"]\n',
     '    allowed = bounty["document_hosts"]\n'),
    ('submission: a document keeps to the document hosts',
     '    allowed = bounty["endpoint_hosts"] if endpoint else bounty["document_hosts"]\n',
     '    allowed = bounty["endpoint_hosts"]\n'),
    ('submission: an endpoint carries no query',
     '            if "?" in canonical_url:\n',
     '            if False:\n'),
    ('submission: a base with or without its slash is one base',
     '            base = canonical_url[:-1] if canonical_url.endswith("/") else canonical_url\n',
     '            base = canonical_url\n'),
    ('submission: a base leaves room for the paths',
     '            if len(base) + _longest_path(bounty, field["id"]) > URL_CAP:\n',
     '            if False:\n'),
    ('submission: a digest is a digest',
     '        if not _is_hex(value["sha256"], 64):\n',
     '        if False:\n'),
    ('submission: an empty file is no document',
     '        if value["sha256"] == EMPTY_SHA256:\n',
     '        if False:\n'),
    ('submission: two documents are two files',
     '        if value["sha256"] in digests:\n',
     '        if False:\n'),
    ('submission: addresses are bounded',
     '        if not isinstance(value["urls"], list) or len(value["urls"]) < 1 \\\n                or len(value["urls"]) > MAX_URLS:\n',
     '        if not isinstance(value["urls"], list):\n'),
    ('submission: no URL twice',
     '            if canonical_url in urls:\n',
     '            if False:\n'),
    ('submission: the commitment covers the endpoint',
     '        + [[field_id, endpoints[field_id]] for field_id in sorted(endpoints.keys())]',
     '        + []'),
    ('check: the exact status',
     '        return MET if answer["status"] == value else NOT_MET',
     '        return MET if answer["status"] < 400 else NOT_MET'),
    ('check: no answer meets nothing',
     '    if answer is None:\n        return NOT_MET',
     '    if answer is None:\n        return MET'),
    ('check: a body check needs a 200',
     '    if answer["status"] != 200 or answer["text"] is None:\n',
     '    if answer["text"] is None:\n'),
    ('check: a body that was not read meets nothing',
     '    if answer["status"] != 200 or answer["text"] is None:\n',
     '    if answer["status"] != 200:\n'),
    ('check: an exact string',
     '        return MET if value in answer["text"] else NOT_MET',
     '        return MET if value.lower() in answer["text"].lower() else NOT_MET'),
    ('check: a key is in an object',
     '        return MET if isinstance(parsed, dict) and value in parsed else NOT_MET',
     '        return MET if value in parsed else NOT_MET'),
    ('check: an answer that is not JSON',
     '    except Exception:\n        return NOT_MET\n    if kind == CHECK_RESPONSE_JSON_KEY:',
     '    except Exception:\n        return MET\n    if kind == CHECK_RESPONSE_JSON_KEY:'),
    ('check: NaN is not JSON in an answer',
     '        parsed = json.loads(answer["text"].lstrip(chr(0xFEFF)), parse_constant=_not_json)',
     '        parsed = json.loads(answer["text"].lstrip(chr(0xFEFF)))'),
    ('check: a byte-order mark is not part of an answer',
     '        parsed = json.loads(answer["text"].lstrip(chr(0xFEFF)), parse_constant=_not_json)',
     '        parsed = json.loads(answer["text"], parse_constant=_not_json)'),
    ("check: an answer's shape",
     '    if value == "object":\n        return MET if isinstance(parsed, dict) else NOT_MET\n    if value == "array":\n        return MET if isinstance(parsed, list) else NOT_MET\n    return MET\n\n\ndef _check_state',
     '    return MET\n\n\ndef _check_state'),
    ('check: a document that is not there meets nothing',
     '    if doc is None or doc["raw"] is None:\n        return NOT_MET',
     '    if doc is None or doc["raw"] is None:\n        return MET'),
    ('check: absence is not shown by a part',
     '    if doc["partial"] and kind in WHOLE_DOCUMENT_CHECKS:\n',
     '    if False:\n'),
    ('check: enough words',
     '        return MET if _count_words(doc["text"]) >= value else NOT_MET',
     '        return MET if _count_words(doc["text"]) > 0 else NOT_MET'),
    ('check: a passage is there or is not',
     '    return MET if found == (kind == CHECK_CONTAINS) else NOT_MET',
     '    return MET if found else NOT_MET'),
    ('call: a server error is no answer',
     '    if status >= 500 or status in MOMENTARY_STATUSES:\n',
     '    if status in MOMENTARY_STATUSES:\n'),
    ('call: a momentary refusal is no answer',
     '    if status >= 500 or status in MOMENTARY_STATUSES:\n',
     '    if status >= 500:\n'),
    ('call: what is not a status is no answer and is recorded as none',
     '    if status < 100 or status > 999:\n',
     '    if False:\n'),
    ('call: a failed fetch is no answer',
     '    except Exception:\n        return {"result": PROBE_UNREACHABLE, "status": 0, "bytes": 0, "text": None}',
     '    except Exception:\n        return {"result": PROBE_ANSWERED, "status": 404, "bytes": 0, "text": ""}'),
    ('call: a large body is not looked at',
     '    if len(body) <= PROBE_BYTES_CAP:\n        text = _decode(body, False)',
     '    if True:\n        text = _decode(body, False)'),
    ('call: each URL once',
     '        if url not in called:\n            called[url] = _call(url)',
     '        if True:\n            called[url] = _call(url)'),
    ('call: nothing once a document is unreadable',
     '        if unreadable:\n            probes.append(',
     '        if False:\n            probes.append('),
    ('call: only an answer is checked',
     '        if answer["result"] == PROBE_ANSWERED:\n            answers[need["requirement"]] = answer',
     '        if True:\n            answers[need["requirement"]] = answer'),
    ("call: the path is the bounty's",
     '                       "url": base + requirement["check"]["path"]})',
     '                       "url": base})'),
    ('round: an unreadable document decides nothing',
     '    if any(s["status"] not in READABLE for s in sources):\n        return EVIDENCE_UNREADABLE',
     '    if False:\n        return EVIDENCE_UNREADABLE'),
    ('round: an unanswered call decides nothing',
     '    if any(entry["result"] != PROBE_ANSWERED for entry in probes):\n',
     '    if False:\n'),
    ('round: a document that addresses the evaluator earns no reading',
     '    if len(markers) > 0:\n        return "DOCUMENT_ADDRESSES_EVALUATOR"',
     '    if False:\n        return "DOCUMENT_ADDRESSES_EVALUATOR"'),
    ('round: documents with no text earn no reading',
     '    if len(sources) > 0 and all(s["content_digest"] == EMPTY_SHA256 for s in sources):\n',
     '    if False:\n'),
    ('round: a MET that shows nothing is not met',
     '    if state == MET and len(quotes) == 0:\n',
     '    if False:\n'),
    ('round: a quote is grounded',
     '        if grounded is not None and grounded not in quotes and len(quotes) < MAX_QUOTES:\n',
     '        if grounded not in quotes and len(quotes) < MAX_QUOTES:\n'),
    ('round: a spliced quote is dropped',
     '        if _spliced(rq["text"]) or _has_surrogate(rq["text"]):\n',
     '        if False:\n'),
    ('round: half an answer is no answer',
     '        if finding is None:\n            print("[MODEL_OUTPUT_INVALID] no state for " + requirement["id"])\n            return None',
     '        if finding is None:\n            continue'),
    ('round: a state is one of the two',
     '    if state not in STATES:\n        return None',
     '    if state not in STATES:\n        state = MET'),
    ('round: the panel is not shown the endpoint',
     '        "documents": items,\n    }',
     '        "documents": items, "endpoints": ctx["endpoints"],\n    }'),
    ('round: the panel judges only the judged',
     '        "requirements": [{"id": r["id"], "text": r["text"]} for r in requirements\n                         if r["kind"] == KIND_JUDGED],',
     '        "requirements": [{"id": r["id"], "text": r["text"]} for r in requirements],'),
    ('round: no panel where code decided',
     '    elif reason != "":\n        panel_state = PANEL_SKIPPED\n        read = [_code_finding(r) for r in judged]',
     '    elif False:\n        panel_state = PANEL_SKIPPED\n        read = [_code_finding(r) for r in judged]'),
    ('round: no panel for checks alone',
     '    elif len(judged) == 0:\n        panel_state = PANEL_NOT_NEEDED\n        read = []',
     '    elif False:\n        panel_state = PANEL_NOT_NEEDED\n        read = []'),
    ("gate: exactly the payload's keys",
     '    if not isinstance(p, dict) or sorted(p.keys()) != sorted(PAYLOAD_KEYS):\n',
     '    if not isinstance(p, dict):\n'),
    ('gate: this round of this submission',
     '    if p["schema"] != SCHEMA_VERSION or p["mode"] != ctx["mode"] \\\n            or p["submission_id"] != ctx["submission_id"] or not _is_int(p["round"]) \\\n            or p["round"] != ctx["round"] or p["bounty_hash"] != ctx["bounty_hash"] \\\n            or p["commitment"] != ctx["commitment"] or p["now"] != ctx["now"]:\n',
     '    if False:\n'),
    ('gate: one source for each document',
     '    if not isinstance(sources, list) or len(sources) != len(items):\n',
     '    if not isinstance(sources, list):\n'),
    ('gate: one probe for every call',
     '    if not isinstance(probes, list) or len(probes) != len(needed):\n',
     '    if not isinstance(probes, list):\n'),
    ('gate: a probe is the call the requirement makes',
     '        if entry["requirement"] != needed[i]["requirement"] or entry["url"] != needed[i]["url"]:\n',
     '        if False:\n'),
    ('gate: a probe result from the list',
     '        if not isinstance(entry["result"], str) or entry["result"] not in PROBE_RESULTS:\n',
     '        if False:\n'),
    ("gate: a probe's numbers are numbers in range",
     '        if not _is_int(entry["http_status"]) or not _is_int(entry["byte_count"]) \\\n                or entry["http_status"] < 0 or entry["http_status"] > 999 \\\n                or entry["byte_count"] < 0 or entry["byte_count"] > MAX_PROBE_BYTES:\n',
     '        if False:\n'),
    ("gate: an answer has an answer's status",
     '        if entry["result"] == PROBE_ANSWERED \\\n                and (not (100 <= entry["http_status"] < 500)\n                     or entry["http_status"] in MOMENTARY_STATUSES):\n',
     '        if False:\n'),
    ('gate: a call not made has no status',
     '        if entry["result"] == PROBE_NOT_ASKED \\\n                and (entry["http_status"] != 0 or entry["byte_count"] != 0):\n',
     '        if False:\n'),
    ('gate: every call was made or none',
     '    return len(unasked) in (0, len(probes))',
     '    return True'),
    ('gate: calls are made exactly when the documents were read',
     '    if len(p["probes"]) > 0 and unreadable != (p["probes"][0]["result"] == PROBE_NOT_ASKED):\n',
     '    if False:\n'),
    ('gate: the reason is recomputed',
     '    if p["panel_reason"] != reason:\n        return None',
     '    if False:\n        return None'),
    ('gate: a round that decides nothing reports no findings',
     '        return p if findings == [] else None',
     '        return p'),
    ('gate: one finding for each requirement',
     '    if len(findings) != len(requirements):\n        return None',
     '    if len(findings) > len(requirements):\n        return None'),
    ('gate: a check is recomputed',
     '        return check_state is None or f["state"] == check_state',
     '        return True'),
    ("gate: a check is code's",
     '        if f["by"] != BY_CODE or f["quotes"] != [] or f["note"] != "":\n            return False\n        return check_state',
     '        return check_state'),
    ('gate: no reading where code decided',
     '        return f["by"] == BY_CODE and f["state"] == NOT_MET and f["quotes"] == [] \\\n            and f["note"] == ""',
     '        return True'),
    ("gate: a judged finding is the panel's",
     '    if f["by"] != BY_PANEL:\n        return False',
     '    if False:\n        return False'),
    ('gate: a MET quotes',
     '    if f["state"] == MET:\n        return len(f["quotes"]) > 0',
     '    if f["state"] == MET:\n        return True'),
    ("gate: a quote is in this node's text",
     '        if q in seen or _spliced(q["text"]) or not _quote_grounded(q, eligible, tokens):\n',
     '        if q in seen or _spliced(q["text"]):\n'),
    ('gate: a status does not contradict a RESPONDS state',
     '                if met != (status == check["value"]):\n                    return None',
     '                if False:\n                    return None'),
    ('gate: a body check met needs a 200 on record',
     '            elif met and status != 200:\n                return None',
     '            elif False:\n                return None'),
    ('gate: a title that cannot be encoded is refused',
     ' or _has_surrogate(sources[i]["title"]):',
     ':'),
    ('verdict: every requirement must be met',
     '        if states.get(requirement["id"]) != MET:\n            return REJECTED',
     '        if False:\n            return REJECTED'),
    ('derive: an unreachable deliverable decides nothing',
     '    if reason in UNAVAILABLE_REASONS:\n        nothing = DELIVERABLE_UNAVAILABLE',
     '    if False:\n        nothing = DELIVERABLE_UNAVAILABLE'),
    ('derive: an unusable answer decides nothing',
     '    elif payload["panel_state"] == PANEL_INVALID:\n        nothing = PANEL_UNUSABLE',
     '    elif False:\n        nothing = PANEL_UNUSABLE'),
    ('compare: the reason a round decides nothing',
     '    if own["panel_reason"] != theirs["panel_reason"]:\n',
     '    if False:\n'),
    ('compare: the markers',
     '    if own["markers"] != theirs["markers"]:\n',
     '    if False:\n'),
    ('compare: whether each call was answered',
     '        if own["probes"][i]["result"] != theirs["probes"][i]["result"]:\n',
     '        if False:\n'),
    ('compare: what a node could do with a document',
     '        if _status_class(mine["status"]) != _status_class(yours["status"]):\n',
     '        if False:\n'),
    ('compare: what was read of a document',
     '            if mine[key] != yours[key]:\n',
     '            if False:\n'),
    ('compare: the consequence',
     '        difference = _consequence_difference(_derive(ctx, own), _derive(ctx, parsed))\n        if difference != "":\n',
     '        difference = ""\n        if difference != "":\n'),
    ('compare: the evidence',
     '        difference = _evidence_difference(ctx, own, parsed)\n        if difference != "":\n',
     '        difference = ""\n        if difference != "":\n'),
    ('compare: the gate',
     '        if parsed is None:\n            print("[DISAGREE] leader payload failed the structural gate")\n            return False',
     '        if parsed is None:\n            return True'),
    ('record: a round that decides nothing records only what was agreed',
     '            if derived["available"]:\n                # only a round',
     '            if True:\n                # only a round'),
    ('record: no marker from a round that decides nothing',
     '            "markers": payload["markers"] if derived["available"] else [],',
     '            "markers": payload["markers"],'),
    ('record: a round that decides nothing is not applied',
     '        if derived["available"]:\n            submission.verdict = derived["outcome"]',
     '        if True:\n            submission.verdict = derived["outcome"]'),
    ('record: the ratified payload is gated again',
     '        if payload is None:\n            raise gl.vm.UserError(ERROR_EXPECTED + " the ratified payload failed the gate")',
     '        if False:\n            raise gl.vm.UserError(ERROR_EXPECTED + " the ratified payload failed the gate")'),
    ('create: a deadline leaves time',
     '        if submit_by < _iso_epoch(now) + MIN_LEAD:\n',
     '        if False:\n'),
    ('create: a deadline is not too far',
     '        if submit_by > _iso_epoch(now) + MAX_AHEAD:\n',
     '        if False:\n'),
    ('fund: only the sponsor',
     '        elif self._sender_hex() != str(bounty.sponsor):\n            refusal = "only the sponsor funds its bounty"\n',
     ''),
    ('fund: only a created bounty',
     '        elif str(bounty.status) != BN_CREATED:\n            refusal = "only a CREATED bounty is funded"\n',
     ''),
    ('fund: exactly the reward',
     '        elif value != int(bounty.reward):\n',
     '        elif value < int(bounty.reward):\n'),
    ('fund: not when the deadline is near',
     '        elif at + MIN_LEAD > _iso_epoch(self._definition(bounty)["submit_by"]):\n',
     '        elif False:\n'),
    ('fund: the reward is held',
     '        bounty.funded_at = now\n        self.escrow_held = u256(int(self.escrow_held) + value)',
     '        bounty.funded_at = now'),
    ('refuse: value attached goes back',
     '        self._pay(self._sender_hex(), value)\n        return RETURNED',
     '        return RETURNED'),
    ('refuse: with no value it fails',
     '        if value == 0:\n            self._fail(refusal)\n        self.returned_count',
     '        self.returned_count'),
    ('cancel: only the sponsor',
     '            self._fail("only the sponsor cancels its bounty")',
     '            pass'),
    ('cancel: not once somebody has submitted',
     '        elif str(bounty.status) == BN_FUNDED and int(bounty.submissions) == 0:\n',
     '        elif str(bounty.status) == BN_FUNDED:\n'),
    ('cancel: a funded bounty gives its reward back',
     '            bounty.closed_by = BY_CANCEL_FUNDED\n            self._out_of_escrow(str(bounty.sponsor), int(bounty.reward))',
     '            bounty.closed_by = BY_CANCEL_FUNDED'),
    ('close: only a funded bounty',
     '            self._fail("only a FUNDED bounty is closed")',
     '            pass'),
    ('close: only after the deadline',
     '        if _iso_epoch(now) <= _iso_epoch(definition["submit_by"]):\n',
     '        if False:\n'),
    ('close: not over an open submission',
     '        if len(open_ids) > 0:\n            self._fail("a submission is still open: " + open_ids[0])',
     '        if False:\n            self._fail("a submission is still open: " + open_ids[0])'),
    ('close: the reward goes back',
     '        bounty.closed_by = BY_NO_ACCEPTANCE\n        bounty.closed_at = now\n        self._out_of_escrow(str(bounty.sponsor), int(bounty.reward))',
     '        bounty.closed_by = BY_NO_ACCEPTANCE\n        bounty.closed_at = now'),
    ('submit: only to a funded bounty',
     '        elif str(bounty.status) != BN_FUNDED:\n            refusal = "only a FUNDED bounty takes submissions"\n',
     ''),
    ('submit: not the sponsor',
     '        elif sender == str(bounty.sponsor):\n            refusal = "a sponsor does not submit to its own bounty"\n',
     ''),
    ('submit: not after the deadline',
     '            if at > _iso_epoch(definition["submit_by"]):\n',
     '            if False:\n'),
    ('submit: exactly the bond',
     '            elif value != int(bounty.bond):\n',
     '            elif value < int(bounty.bond):\n'),
    ('submit: one open submission each',
     '            elif still_open is not None and str(still_open) != "":\n',
     '            elif False:\n'),
    ('submit: attempts are capped',
     '            elif made is not None and int(made) >= MAX_ATTEMPTS:\n',
     '            elif False:\n'),
    ('submit: open submissions are capped',
     '            elif len(json.loads(str(bounty.open_ids))) >= MAX_OPEN:\n',
     '            elif False:\n'),
    ('submit: the bond is held',
     '        self.open_of[pair] = submission_id\n        self.escrow_held = u256(int(self.escrow_held) + value)',
     '        self.open_of[pair] = submission_id'),
    ('submit: the read-by time is fixed at submission',
     '            read_by=_epoch_iso(at + definition["evaluate_window"]), window_ends="",',
     '            read_by=_epoch_iso(at + definition["contest_window"]), window_ends="",'),
    ('mirror: only the developer',
     '            self._fail("only the developer adds an address to its submission")',
     '            pass'),
    ('mirror: not once final',
     '            self._fail("an address is added to a submission that is not yet final")',
     '            pass'),
    ('mirror: on a host the bounty allows',
     '        error, canonical_url = _admitted_url(url, definition)\n',
     '        error, canonical_url = _url_parts(url)\n'),
    ('mirror: only a document',
     '        if target is None:\n            self._fail("field is not a document of this submission")',
     '        if target is None:\n            return ""'),
    ('mirror: no URL twice',
     '                self._fail("this submission already lists that URL")',
     '                pass'),
    ('mirror: addresses are capped',
     '        if len(target["urls"]) >= MAX_URLS:\n',
     '        if False:\n'),
    ('evaluate: only a submitted submission',
     '            self._fail("only a SUBMITTED submission is evaluated")',
     '            pass'),
    ('evaluate: only until the read-by time',
     '            self._fail("this submission was to be read by " + str(submission.read_by))',
     '            pass'),
    ('evaluate: rounds are capped',
     '        if rounds >= MAX_EVALUATE_ROUNDS:\n',
     '        if False:\n'),
    ("evaluate: after an unreachable deliverable the retries are the developer's",
     '        if str(submission.open_round) in UNAVAILABLE_REASONS \\\n                and sender != str(submission.developer):\n',
     '        if False:\n'),
    ("evaluate: after an unusable answer the retries are the two parties'",
     '        if str(submission.open_round) == PANEL_UNUSABLE \\\n                and sender not in (str(submission.developer), str(submission.sponsor)):\n',
     '        if False:\n'),
    ('evaluate: a round is counted',
     '        submission.evaluate_rounds = u32(rounds + 1)',
     '        pass'),
    ('evaluate: a round that decides nothing leaves it submitted',
     '        if derived["available"]:\n            definition = self._definition(self._bounty(str(submission.bounty_id)))\n            submission.status = ST_EVALUATED',
     '        if True:\n            definition = self._definition(self._bounty(str(submission.bounty_id)))\n            submission.status = ST_EVALUATED'),
    ('evaluate: why a round decided nothing is kept',
     '            submission.open_round = derived["reason_code"]\n',
     '            pass\n'),
    ('evaluate: when a round decided nothing is kept',
     '                submission.open_round_at = now\n',
     '                pass\n'),
    ('evaluate: still not being there buys no more grace',
     '            if not (derived["reason_code"] in UNAVAILABLE_REASONS\n                    and str(submission.open_round) in UNAVAILABLE_REASONS):\n',
     '            if True:\n'),
    ('evaluate: going missing again starts a new grace',
     '                    and str(submission.open_round) in UNAVAILABLE_REASONS):\n',
     '                    and str(submission.open_round) != ""):\n'),
    ('evaluate: an unusable answer after a missing one is timed',
     '            if not (derived["reason_code"] in UNAVAILABLE_REASONS\n',
     '            if not (str(submission.open_round) != ""\n'),
    ('evaluate: a reading clears when the last round failed',
     '            submission.open_round_at = ""\n',
     ''),
    ('contest: each doubt has its own restore rounds',
     '            submission.restore_rounds = u32(0)\n',
     ''),
    ('url: a last label that begins with a digit is no name',
     '    if all_numeric or labels[-1][0].isdigit():',
     '    if all_numeric or labels[-1].isdigit():'),
    ('fetch: a status that is not one is recorded as none',
     '        if code < 0 or code > 999:\n            code = 0\n',
     ''),
    ('evaluate: a reading clears what the last round could not do',
     '            submission.status = ST_EVALUATED\n            submission.open_round = ""',
     '            submission.status = ST_EVALUATED'),
    ('contest: only an evaluated submission',
     '            self._fail("only an EVALUATED submission is contested")',
     '            pass'),
    ('contest: only the two parties',
     '            self._fail("only the developer or the sponsor contests an evaluation")',
     '            pass'),
    ('contest: not while in doubt',
     '        if bool(submission.in_doubt):\n            self._fail("the acceptance is in doubt: only the developer\'s restore reads"',
     '        if False:\n            self._fail("the acceptance is in doubt: only the developer\'s restore reads"'),
    ('contest: a sponsor contests an acceptance',
     '            self._fail("a sponsor contests an acceptance")',
     '            pass'),
    ('contest: a developer contests a rejection',
     '            self._fail("a developer contests a rejection")',
     '            pass'),
    ('contest: one read contest each',
     '            self._fail("this party has contested this submission once already")',
     '            pass'),
    ('contest: rounds are capped',
     '        if asked >= MAX_CONTEST_ROUNDS:\n',
     '        if False:\n'),
    ('contest: only inside the window',
     '            self._fail("the contest window closed at " + str(submission.window_ends))\n        evaluation_id, derived = self._round(submission, MODE_CONTEST, now)',
     '            pass\n        evaluation_id, derived = self._round(submission, MODE_CONTEST, now)'),
    ("contest: the sponsor's round is the sponsor's",
     '        if by_sponsor:\n            submission.sponsor_contests = u32(asked + 1)\n        else:\n            submission.developer_contests = u32(asked + 1)',
     '        submission.developer_contests = u32(asked + 1)'),
    ('contest: a round is counted',
     '            submission.sponsor_contests = u32(asked + 1)\n        else:\n            submission.developer_contests = u32(asked + 1)',
     '            pass\n        else:\n            pass'),
    ('contest: a read contest is used',
     '            if by_sponsor:\n                submission.sponsor_contested = True\n            else:\n                submission.developer_contested = True',
     '            pass'),
    ('contest: an unreachable deliverable puts an acceptance in doubt',
     '            submission.in_doubt = True',
     '            pass'),
    ("contest: a developer's unreachable contest raises no doubt",
     '        elif by_sponsor and derived["reason_code"] in UNAVAILABLE_REASONS:\n',
     '        elif derived["reason_code"] in UNAVAILABLE_REASONS:\n'),
    ('contest: an unusable answer raises no doubt',
     '        elif by_sponsor and derived["reason_code"] in UNAVAILABLE_REASONS:\n',
     '        elif by_sponsor:\n'),
    ('contest: every round starts the window again',
     '            submission.restore_rounds = u32(0)\n        definition = self._definition(self._bounty(str(submission.bounty_id)))\n        submission.window_ends = _epoch_iso(_iso_epoch(now) + definition["contest_window"])',
     '            submission.restore_rounds = u32(0)'),
    ('restore: only an acceptance in doubt',
     '            self._fail("only an acceptance in doubt is restored")',
     '            pass'),
    ('restore: only the developer',
     '            self._fail("only the developer restores its deliverable")',
     '            pass'),
    ('restore: rounds are capped',
     '        if asked >= MAX_RESTORE_ROUNDS:\n',
     '        if False:\n'),
    ('restore: only inside the window',
     '            self._fail("the contest window closed at " + str(submission.window_ends))\n        evaluation_id, derived = self._round(submission, MODE_RESTORE, now)',
     '            pass\n        evaluation_id, derived = self._round(submission, MODE_RESTORE, now)'),
    ('restore: a round is counted',
     '        submission.restore_rounds = u32(asked + 1)',
     '        pass'),
    ('restore: a deliverable still unreachable stays in doubt',
     '        if derived["reason_code"] not in UNAVAILABLE_REASONS:\n',
     '        if True:\n'),
    ('restore: a deliverable that is back is out of doubt whatever the model says',
     '        if derived["reason_code"] not in UNAVAILABLE_REASONS:\n',
     '        if derived["available"]:\n'),
    ("restore: only a reading answers the sponsor's contest",
     '        if derived["available"]:\n            submission.sponsor_contested = True',
     '        if True:\n            submission.sponsor_contested = True'),
    ("restore: a reading answers the sponsor's contest",
     '        if derived["available"]:\n            submission.sponsor_contested = True',
     '        if False:\n            submission.sponsor_contested = True'),
    ('restore: the window starts again',
     '            submission.sponsor_contested = True\n        definition = self._definition(self._bounty(str(submission.bounty_id)))\n        submission.window_ends = _epoch_iso(_iso_epoch(now) + definition["contest_window"])',
     '            submission.sponsor_contested = True'),
    ('finalize: only an evaluated submission',
     '            self._fail("only an EVALUATED submission is finalized")',
     '            pass'),
    ('finalize: only after the window',
     '            self._fail("the contest window closes at " + str(submission.window_ends))',
     '            pass'),
    ('finalize: an acceptance in doubt is rejected',
     '        if bool(submission.in_doubt):\n            self._end(bounty, submission, RES_REJECTED, WHY_GONE, now)\n            return RES_REJECTED\n        if str(submission.verdict) != ACCEPTED:',
     '        if str(submission.verdict) != ACCEPTED:'),
    ('finalize: a rejection is not paid',
     '        if str(submission.verdict) != ACCEPTED:\n            self._end(bounty, submission, RES_REJECTED, WHY_EVALUATED, now)\n            return RES_REJECTED',
     '        if False:\n            self._end(bounty, submission, RES_REJECTED, WHY_EVALUATED, now)\n            return RES_REJECTED'),
    ('finalize: an earlier submission is first in line',
     '        if earlier != "":\n            self._fail("an earlier submission may still be accepted and is first in"',
     '        if False:\n            self._fail("an earlier submission may still be accepted and is first in"'),
    ('finalize: the reward goes to the developer',
     '        bounty.winning_submission = str(submission.submission_id)\n        self._out_of_escrow(str(submission.developer), int(bounty.reward))',
     '        bounty.winning_submission = str(submission.submission_id)\n        self._out_of_escrow(str(bounty.sponsor), int(bounty.reward))'),
    ('finalize: the bounty is released',
     '        bounty.status = BN_RELEASED\n',
     ''),
    ('finalize: the other open submissions end with the bounty',
     '        for other_id in json.loads(str(bounty.open_ids)):\n            self._end_with_bounty(bounty, self.submissions.get(other_id), at, now)',
     '        pass'),
    ('lapse: only a submitted submission',
     '            self._fail("only a SUBMITTED submission lapses")',
     '            pass'),
    ('lapse: only after the read-by time',
     '            self._fail("this submission may be read until " + str(submission.read_by))',
     '            pass'),
    ('lapse: an unreachable deliverable is named',
     '        if str(submission.open_round) in UNAVAILABLE_REASONS:\n            return WHY_UNREADABLE',
     '        if False:\n            return WHY_UNREADABLE'),
    ('lapse: nobody asking is named',
     '        if int(submission.evaluate_rounds) == 0:\n            return WHY_NO_EVALUATION',
     '        if False:\n            return WHY_NO_EVALUATION'),
    ('end: a bond comes back when paid or outrun',
     '        if result in (RES_PAID, RES_OUTRUN):\n',
     '        if result == RES_PAID:\n'),
    ('end: a bond is forfeit when rejected or never read',
     '        if result in (RES_PAID, RES_OUTRUN):\n',
     '        if True:\n'),
    ('end: a forfeit bond goes to the sponsor',
     '            self._out_of_escrow(str(bounty.sponsor), bond)',
     '            self._out_of_escrow(str(submission.developer), bond)'),
    ('end: the submission leaves the open list',
     '        bounty.open_ids = _canonical(open_ids)\n        self.open_of[self._pair(str(bounty.bounty_id)',
     '        self.open_of[self._pair(str(bounty.bounty_id)'),
    ('end: the developer may submit again',
     '        self.open_of[self._pair(str(bounty.bounty_id), str(submission.developer))] = ""',
     '        pass'),
    ('end: a verdict that rests on no reading has no record',
     '            submission.standing_evaluation = ""\n            submission.reason_code = ""',
     '            submission.reason_code = ""'),
    ('end: a doubt ends with the submission',
     '        submission.final_at = now\n        submission.in_doubt = False',
     '        submission.final_at = now'),
    ('end with the bounty: one that held a place is outrun',
     '        if self._may_still_win(submission, at):\n            self._end(bounty, submission, RES_OUTRUN, WHY_BOUNTY_PAID, now)',
     '        if False:\n            self._end(bounty, submission, RES_OUTRUN, WHY_BOUNTY_PAID, now)'),
    ('end with the bounty: one that held none is not outrun',
     '        if self._may_still_win(submission, at):\n            self._end(bounty, submission, RES_OUTRUN, WHY_BOUNTY_PAID, now)',
     '        if True:\n            self._end(bounty, submission, RES_OUTRUN, WHY_BOUNTY_PAID, now)'),
    ('end with the bounty: unread it was never read',
     '        elif str(submission.status) == ST_SUBMITTED:\n            self._end(bounty, submission, RES_NOT_READ, self._unread_reason(submission), now)',
     '        elif False:\n            self._end(bounty, submission, RES_NOT_READ, self._unread_reason(submission), now)'),
    ('end with the bounty: in doubt it is gone',
     '        elif bool(submission.in_doubt):\n            self._end(bounty, submission, RES_REJECTED, WHY_GONE, now)\n        else:',
     '        elif False:\n            self._end(bounty, submission, RES_REJECTED, WHY_GONE, now)\n        else:'),
    ('place: asked for and not there holds none after the grace',
     '            if str(submission.open_round) in UNAVAILABLE_REASONS \\\n                    and at > _iso_epoch(str(submission.open_round_at)) + RETRY_GRACE:\n                return False',
     '            if False:\n                return False'),
    ('place: asked for and not there keeps it through the grace',
     '                    and at > _iso_epoch(str(submission.open_round_at)) + RETRY_GRACE:\n',
     '                    and True:\n'),
    ('place: the grace runs from the round that found it missing',
     '                    and at > _iso_epoch(str(submission.open_round_at)) + RETRY_GRACE:\n',
     '                    and at > _iso_epoch(str(submission.submitted_at)) + RETRY_GRACE:\n'),
    ('place: an unusable answer costs no place',
     '            if str(submission.open_round) in UNAVAILABLE_REASONS \\\n                    and at > _iso_epoch(str(submission.open_round_at)) + RETRY_GRACE:\n',
     '            if str(submission.open_round) != "" \\\n                    and at > _iso_epoch(str(submission.open_round_at)) + RETRY_GRACE:\n'),
    ('place: no round left holds none',
     '            if int(submission.evaluate_rounds) >= MAX_EVALUATE_ROUNDS:\n                return False',
     '            if False:\n                return False'),
    ('place: unread holds until its read-by time',
     '            return at <= _iso_epoch(str(submission.read_by))\n        if str(submission.status) != ST_EVALUATED:',
     '            return True\n        if str(submission.status) != ST_EVALUATED:'),
    ('place: unread holds its place',
     '            return at <= _iso_epoch(str(submission.read_by))\n        if str(submission.status) != ST_EVALUATED:',
     '            return False\n        if str(submission.status) != ST_EVALUATED:'),
    ('place: an acceptance holds until it is finalized',
     '            return not bool(submission.in_doubt) or (\n',
     '            return False or (\n'),
    ('place: an acceptance in doubt past its window holds none',
     '                in_window and int(submission.restore_rounds) < MAX_RESTORE_ROUNDS)',
     '                int(submission.restore_rounds) < MAX_RESTORE_ROUNDS)'),
    ('place: an acceptance in doubt with no restore round left holds none',
     '                in_window and int(submission.restore_rounds) < MAX_RESTORE_ROUNDS)',
     '                in_window)'),
    ('place: a rejection holds only inside its window',
     '        return in_window and not bool(submission.developer_contested) \\\n',
     '        return not bool(submission.developer_contested) \\\n'),
    ('place: a rejection already contested holds none',
     '        return in_window and not bool(submission.developer_contested) \\\n',
     '        return in_window \\\n'),
    ('place: a rejection with no contest round left holds none',
     '            and int(submission.developer_contests) < MAX_CONTEST_ROUNDS\n\n    def _earlier_claim',
     '            and True\n\n    def _earlier_claim'),
    ('place: only an earlier submission is first',
     '            if int(other.sequence) < int(submission.sequence) \\\n',
     '            if True \\\n'),
    ('withdraw: nothing to withdraw',
     '            self._fail("nothing to withdraw")',
     '            return "0"'),
    ('withdraw: the balance is cleared',
     '        self.balances[wallet] = u256(0)\n',
     ''),
    ('withdraw: what is owed goes down',
     '        self.balances_owed = u256(int(self.balances_owed) - amount)\n        self._pay(wallet, amount)',
     '        self._pay(wallet, amount)'),
    ('withdraw: the wallet is paid',
     '        self.balances_owed = u256(int(self.balances_owed) - amount)\n        self._pay(wallet, amount)',
     '        self.balances_owed = u256(int(self.balances_owed) - amount)'),
    ('credit: what is owed goes up',
     '        self.balances_owed = u256(int(self.balances_owed) + amount)',
     '        pass'),
    ('escrow: what leaves is no longer held',
     '        self.escrow_held = u256(int(self.escrow_held) - amount)\n        self._credit(wallet, amount)',
     '        self._credit(wallet, amount)'),
    ('actions: evaluate while readable and rounds are left',
     '            "may_evaluate": readable\n            and int(submission.evaluate_rounds) < MAX_EVALUATE_ROUNDS,',
     '            "may_evaluate": readable,'),
    ('actions: lapse after the read-by time',
     '            "may_lapse": submitted and not readable,',
     '            "may_lapse": submitted,'),
    ('actions: a developer contests a rejection',
     '        developer_may = window_open and not in_doubt and verdict == REJECTED \\\n',
     '        developer_may = window_open and not in_doubt \\\n'),
    ('actions: a sponsor contests an acceptance',
     '        sponsor_may = window_open and not in_doubt and verdict == ACCEPTED \\\n',
     '        sponsor_may = window_open and not in_doubt \\\n'),
    ('actions: restore while in doubt and rounds are left',
     '            "may_restore": window_open and in_doubt\n            and int(submission.restore_rounds) < MAX_RESTORE_ROUNDS,',
     '            "may_restore": window_open and in_doubt,'),
    ('actions: finalize waits for an earlier submission',
     '            "may_finalize": may_finalize and waits_for == "",',
     '            "may_finalize": may_finalize,'),
    ('actions: fund while the deadline leaves time',
     '            "may_fund": status == BN_CREATED and at + MIN_LEAD <= submit_by,',
     '            "may_fund": status == BN_CREATED,'),
    ('actions: cancel before any submission',
     '            or (status == BN_FUNDED and int(bounty.submissions) == 0),',
     '            or status == BN_FUNDED,'),
    ('actions: submit while places are open',
     '            and len(open_ids) < MAX_OPEN,',
     '            and True,'),
    ('actions: close after the deadline with nothing open',
     '            "may_close": status == BN_FUNDED and at > submit_by and len(open_ids) == 0,',
     '            "may_close": status == BN_FUNDED and at > submit_by,'),
    ('view: a balance is read by its lowercase address',
     '        key = wallet.lower() if isinstance(wallet, str) else ""',
     '        key = wallet if isinstance(wallet, str) else ""'),
    ('view: a page is bounded',
     '        limit = min(limit, PAGE_LIMIT)\n',
     ''),
    ('header: a header value that is bytes is read',
     '                if isinstance(value, (bytes, bytearray)):\n',
     '                if False:\n'),
]


def run_suite(workdir: pathlib.Path) -> bool:
    completed = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/direct", "-q", "-x", "-p", "no:cacheprovider",
         "--no-header"], cwd=workdir, capture_output=True, text=True)
    return completed.returncode == 0


def check_anchors(source: str) -> int:
    missing = 0
    for name, old, _new in MUTATIONS:
        hits = source.count(old)
        if hits != 1:
            print(f"ANCHOR MISSING ({hits} hits): {name}")
            missing += 1
    return missing


def copy_repo(scratch: pathlib.Path, index: int) -> pathlib.Path:
    work = scratch / ("repo%d" % index)
    shutil.copytree(ROOT, work, ignore=shutil.ignore_patterns(
        ".git", "__pycache__", ".pytest_cache", "deploy", "artifacts", ".data", "docs"))
    return work


def main() -> None:
    source = (ROOT / CONTRACT).read_text(encoding="utf-8")
    missing = check_anchors(source)
    print(f"{len(MUTATIONS)} mutations, {missing} anchor problems")
    if "--anchors" in sys.argv:
        sys.exit(0 if missing == 0 else 1)
    only = ""
    if "--only" in sys.argv:
        only = sys.argv[sys.argv.index("--only") + 1].casefold()
    jobs = 1
    if "--jobs" in sys.argv:
        jobs = max(1, int(sys.argv[sys.argv.index("--jobs") + 1]))
    todo = [x for x in MUTATIONS if source.count(x[1]) == 1
            and (not only or any(part in x[0].casefold() for part in only.split("|")))]
    carried = set()
    if "--resume" in sys.argv:
        # a sweep cut short continues: mutations an earlier pass of the same
        # contract already killed are carried over, not run again
        earlier = pathlib.Path(sys.argv[sys.argv.index("--resume") + 1])
        for line in earlier.read_text(encoding="utf-8").splitlines():
            if "] killed  : " in line:
                carried.add(line.split("] killed  : ", 1)[1])
        todo = [x for x in todo if x[0] not in carried]
        print(f"carried over from {earlier.name}: {len(carried)} killed")
    jobs = min(jobs, max(1, len(todo)))
    scratch = pathlib.Path(tempfile.mkdtemp(prefix="ba-mut-"))
    copies = [copy_repo(scratch, i) for i in range(jobs)]
    print("accept-control: unmodified copy must pass ...", flush=True)
    if not run_suite(copies[0]):
        print("CONTROL FAILED: the unmodified suite does not pass; aborting")
        shutil.rmtree(scratch, ignore_errors=True)
        sys.exit(1)
    print(f"control green; {len(todo)} mutations over {jobs} job(s)\n", flush=True)
    results = [None] * len(todo)
    cursor = [0]
    done = [0]
    lock = threading.Lock()

    def worker(work: pathlib.Path) -> None:
        target = work / CONTRACT
        while True:
            with lock:
                i = cursor[0]
                if i >= len(todo):
                    return
                cursor[0] = i + 1
            name, old, new = todo[i]
            target.write_text(source.replace(old, new), encoding="utf-8", newline="\n")
            passed = run_suite(work)
            target.write_text(source, encoding="utf-8", newline="\n")
            with lock:
                results[i] = passed
                done[0] += 1
                print(f"  [{done[0]}/{len(todo)}] {'SURVIVED' if passed else 'killed  '}: "
                      f"{name}", flush=True)

    threads = [threading.Thread(target=worker, args=(w,)) for w in copies]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    shutil.rmtree(scratch, ignore_errors=True)
    print()
    killed = survived = 0
    for name in sorted(carried):
        print("killed:   " + name)
        killed += 1
    for (name, _old, _new), passed in zip(todo, results):
        print(("SURVIVED: " if passed else "killed:   ") + name)
        survived += 1 if passed else 0
        killed += 0 if passed else 1
    print(f"\nmutations: {killed} killed, {survived} survived, {missing} anchor missing")
    sys.exit(0 if survived == 0 and missing == 0 else 1)


if __name__ == "__main__":
    main()
